INSERT INTO recipe (name, description, imageURL) VALUES
                                                     ('Chocolate Cake', 'A rich and moist chocolate cake', 'https://example.com/chocolate-cake.jpg'),
                                                     ('Vanilla Cupcake', 'Light and fluffy vanilla cupcakes with frosting', 'https://example.com/vanilla-cupcake.jpg'),
                                                     ('Strawberry Cheesecake', 'Creamy cheesecake topped with fresh strawberries', 'https://example.com/strawberry-cheesecake.jpg'),
                                                     ('Lemon Meringue Pie', 'Sweet and tangy pie with fluffy meringue topping', 'https://example.com/lemon-meringue-pie.jpg'),
                                                     ('Banana Bread', 'Moist banana bread with a hint of cinnamon', 'https://example.com/banana-bread.jpg'),
                                                     ('Apple Pie', 'Classic apple pie with a flaky crust', 'https://example.com/apple-pie.jpg'),
                                                     ('Chicken Alfredo', 'Creamy Alfredo pasta with tender chicken', 'https://example.com/chicken-alfredo.jpg'),
                                                     ('Spaghetti Bolognese', 'Traditional Italian pasta with meat sauce', 'https://example.com/spaghetti-bolognese.jpg');

INSERT INTO ingredient (name, quantity, recipe_id) VALUES
                                                       ('Flour', '2 cups', 1),
                                                       ('Sugar', '1.5 cups', 1),
                                                       ('Cocoa Powder', '0.5 cup', 1),
                                                       ('Eggs', '3 large', 1),
                                                       ('Butter', '1 cup', 1),
                                                       ('Flour', '1.5 cups', 2),
                                                       ('Sugar', '1 cup', 2),
                                                       ('Eggs', '2 large', 2),
                                                       ('Butter', '0.5 cup', 2),
                                                       ('Vanilla Extract', '1 tsp', 2),
                                                       ('Cream Cheese', '500g', 3),
                                                       ('Sugar', '1 cup', 3),
                                                       ('Strawberries', '200g', 3),
                                                       ('Graham Crust', '1 base', 3),
                                                       ('Pie Crust', '1 base', 4),
                                                       ('Lemon Juice', '0.5 cup', 4),
                                                       ('Sugar', '1 cup', 4),
                                                       ('Egg Whites', '3 large', 4),
                                                       ('Bananas', '3 ripe', 5),
                                                       ('Flour', '2 cups', 5),
                                                       ('Sugar', '0.75 cup', 5),
                                                       ('Eggs', '2 large', 5),
                                                       ('Butter', '0.5 cup', 5),
                                                       ('Pie Crust', '1 base', 6),
                                                       ('Apples', '4 cups sliced', 6),
                                                       ('Sugar', '0.5 cup', 6),
                                                       ('Cinnamon', '1 tsp', 6),
                                                       ('Chicken Breast', '500g', 7),
                                                       ('Pasta', '300g', 7),
                                                       ('Cream', '1 cup', 7),
                                                       ('Parmesan Cheese', '0.5 cup', 7),
                                                       ('Garlic', '2 cloves', 7),
                                                       ('Spaghetti', '300g', 8),
                                                       ('Ground Beef', '250g', 8),
                                                       ('Tomato Sauce', '1 cup', 8),
                                                       ('Onion', '1 chopped', 8),
                                                       ('Garlic', '2 cloves', 8);

INSERT INTO instructions (recipe_id, step_number, instruction_text) VALUES
                                                                        (1, 1, 'Preheat oven to 350°F (175°C).'),
                                                                        (1, 2, 'Mix dry ingredients together.'),
                                                                        (1, 3, 'Add eggs and butter, mix until smooth.'),
                                                                        (1, 4, 'Pour into pan and bake for 30 minutes.'),
                                                                        (2, 1, 'Preheat oven to 350°F (175°C).'),
                                                                        (2, 2, 'Mix flour, sugar, eggs, butter, and vanilla.'),
                                                                        (2, 3, 'Spoon batter into cupcake liners.'),
                                                                        (2, 4, 'Bake for 20 minutes.'),
                                                                        (3, 1, 'Prepare crust in pan.'),
                                                                        (3, 2, 'Mix cream cheese and sugar until smooth.'),
                                                                        (3, 3, 'Pour filling over crust and chill.'),
                                                                        (3, 4, 'Top with fresh strawberries.'),
                                                                        (4, 1, 'Bake pie crust until golden.'),
                                                                        (4, 2, 'Prepare lemon filling with juice and sugar.'),
                                                                        (4, 3, 'Beat egg whites into stiff peaks.'),
                                                                        (4, 4, 'Spread meringue on top and bake until golden.'),
                                                                        (5, 1, 'Mash bananas in a bowl.'),
                                                                        (5, 2, 'Mix in flour, sugar, eggs, and butter.'),
                                                                        (5, 3, 'Pour batter into loaf pan.'),
                                                                        (5, 4, 'Bake at 350°F (175°C) for 1 hour.'),
                                                                        (6, 1, 'Prepare pie crust.'),
                                                                        (6, 2, 'Mix apples with sugar and cinnamon.'),
                                                                        (6, 3, 'Fill crust with apple mixture.'),
                                                                        (6, 4, 'Bake until golden.'),
                                                                        (7, 1, 'Cook pasta until al dente.'),
                                                                        (7, 2, 'Cook chicken in skillet.'),
                                                                        (7, 3, 'Add cream, garlic, and Parmesan.'),
                                                                        (7, 4, 'Toss pasta with sauce and chicken.'),
                                                                        (8, 1, 'Boil spaghetti until al dente.'),
                                                                        (8, 2, 'Cook onion and garlic, add beef.'),
                                                                        (8, 3, 'Pour in tomato sauce and simmer.'),
                                                                        (8, 4, 'Serve over spaghetti.');
